Dalesbred Reference Documentation
=================================
Juha Komulainen <juha.komulainen@evident.fi>

:jdkJavadocBase: http://download.java.net/jdk8/docs/api/?
:springJavadocBase: http://docs.spring.io/spring/docs/current/javadoc-api/?
:jodaJavadocBase: http://www.joda.org/joda-time/apidocs/?

Basic usage
-----------

Configuring the database connection
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Most things in Dalesbred happen through an instance of {javadocBase}org/dalesbred/Database.html[Database].
The easiest way to get hold of one is to specify the settings manually:

[source,java,indent=0]
----
        Database db = Database.forUrlAndCredentials("jdbc:example-url", "login", "password");
----

Note that this performs no connection pooling and is therefore probably not
your preferred way of configuring the system in production. In a container
you'll probably want to use a named {jdkJavadocBase}javax/sql/DataSource.html[DataSource] lookup up from JNDI:

[source,java,indent=0]
Database db = Database.forJndiDataSource("java:comp/env/jdbc/ExampleDb");

Alternatively, you might setup a {jdkJavadocBase}javax/sql/DataSource.html[DataSource] yourself, in which case you can
just create a {javadocBase}org/dalesbred/Database.html[Database] out of that:

[source,java,indent=0]
Database db = Database.forDataSource(myDataSource);

If you are using http://projects.spring.io/spring-framework/[Spring Framework] or
https://code.google.com/p/google-guice/[Guice], see the <<_integrations,Integrations>>-section
on how to integrate Dalesbred with them.

Finding stuff
~~~~~~~~~~~~~

Finding simple results consisting of just basic types is simple:

[source,java,indent=0]
----
        List<Integer> newIds = db.findAll(Integer.class,
            "select id from department where created_date > ?", date);
----

To fetch results with multiple columns, usually you'd use a class with matching constructor:

[source,java,indent=0]
----
        List<Department> departments =
            db.findAll(Department.class, "select id, name from department");

        public final class Department {
            private final int id;
            private final String name;

            public Department(int id, String name) {
                this.id = id;
                this.name = name;
            }

            ...
        }
----

If there are more columns in the result-set than can be given to a constructor, then the rest of the
columns are set using properties or direct field access. So even the following would work:

[source,java,indent=0]
----
        List<Department> departments =
            db.findAll(Department.class, "select id, name from department");

        ...

        public final class Department {
            public int id;
            public String name;
        }
----

You can also convert the results directly to a map:

[source,java,indent=0]
----
        Map<Integer,String> namesByIds = db.findMap(
                Integer.class, String.class, "select id, name from department");
----

If for some reason you don't want to map the results into your own class, you can ask for
a {javadocBase}org/dalesbred/ResultTable.html[ResultTable], which is basically a detached
representation of a {jdkJavadocBase}java/sql/ResultSet.html[ResultSet]:

[source,java,indent=0]
----
        ResultTable employees = db.findTable("select * from employee");
----

Alternatively, you can supply your own {javadocBase}org/dalesbred/results/RowMapper.html[RowMapper] or
{javadocBase}org/dalesbred/results/ResultSetProcessor.html[ResultSetProcessor]-implementation in place
of the class and handle the result sets manually, but usually this should be unnecessary.

Updates
~~~~~~~

Normal updates are straightforward, since we don't need to do much work to map the results:

[source,java,indent=0]
----
        int modifiedRows = db.update("delete from user where id=?", 42);
----

If you plan to return stuff from updates, they are queries as far as Dalesbred is concerned:

[source,java,indent=0]
----
        int id = db.findUniqueInt("insert into department (name) values ('foo') returning id");
----

Queries
-------

SqlQuery vs. query parameters
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

All methods come in two variants: there's an implementation that takes
an {javadocBase}org/dalesbred/query/SqlQuery.html[SqlQuery] as a parameter and there's another
implementation that takes {jdkJavadocBase}java/lang/String.html[String] and variable arguments of parameters.
The latter is just convenience method for the further, meaning that the following code fragments are
identical in functionality:

[source,java,indent=0]
----
        import static org.dalesbred.query.SqlQuery.query;

        SqlQuery query = query("select id, name from department where update_timestamp > ?", date);
        db.findAll(Department.class, query);

        db.findAll(Department.class,
            "select id, name from department where update_timestamp > ?", date);
----

Normally you want to use the latter form, but every once in a while it's
useful to be able to pass the query around with its parameters. In those
cases you'd want to use the first form. An example is when you build
the query dynamically:

[source,java,indent=0]
----
        db.findAll(Department.class, buildDepartmentQuery(form));
----

Named queries
~~~~~~~~~~~~~

In addition to using positional parameters in your SQL statements, you can also you named parameters:

[source,java,indent=0]
----
        import static org.dalesbred.query.SqlQuery.namedQuery;

        Map<String,Object> values = new HashMap<>();
        values.put("firstName", "John");
        values.put("lastName", "Doe");

        db.findAll(Department.class, namedQuery("select id from employee " +
                                                " where first_name = :firstName " +
                                                "   and last_name = :lastName", values));
----

Instead of {jdkJavadocBase}java/util/Map.html[Map]s, you can also pass just regular objects to `namedQuery` as
the source of values. The parameter names are mapped to properties or fields of the objects. Finally, if you want
detailed control, you can pass your own implementation of
{javadocBase}org/dalesbred/query/VariableResolver.html[VariableResolver] to resolve the variables.

Building queries dynamically
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

At the moment there's no high-level API for building queries, but there is a
{javadocBase}org/dalesbred/query/QueryBuilder.html[QueryBuilder] that
is basically just a {jdkJavadocBase}java/util/StringBuilder.html[StringBuilder] which remembers
the query-parameters, so you can say things like:

[source,java,indent=0]
----
        QueryBuilder qb = new QueryBuilder("select id, name, status from document");
        if (status != null)
            qb.append(" where status=?", status);

        db.findAll(Document.class, qb.build());
----

For all but simplest dynamic queries, you'll probably want to have a higher level API that understands
the structure of the SQL.

Transactions
------------

Transaction callbacks
~~~~~~~~~~~~~~~~~~~~~

To perform a bunch of operations in transaction, use {javadocBase}org/dalesbred/TransactionCallback.html[TransactionCallback]
or {javadocBase}org/dalesbred/VoidTransactionCallback.html[VoidTransactionCallback]:

[source,java,indent=0]
----
        db.withTransaction(tx -> {
            // transactional operations
            ...
            return result;
        });

        db.withVoidTransaction(tx -> {
            // transactional operations
            ...
        });
----

Annotation based transactions
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Instead of using transaction callbacks you can also build transactional proxies for your services:

[source,java,indent=0]
----
        public interface MyService {
             void frobnicate();
        }

        public class MyRealService implements MyService {

             @DalesbredTransactional
             public void frobnicate() {
                 ...
             }
        }

        ...

        MyService myService = db.createTransactionalProxyFor(MyService.class, new MyRealService());
        service.frobnicate(); // this call will have a transaction wrapped around it
----

External transaction manager
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

If you are using http://projects.spring.io/spring-framework/[Spring Framework] or
https://code.google.com/p/google-guice/[Guice], Dalesbred can integrate with them for transaction
management. Consult the <<_integrations,Integrations>>-section for details.

Implicit transactions
~~~~~~~~~~~~~~~~~~~~~

If you make calls to {javadocBase}org/dalesbred/Database.html[Database] without and explicit transaction, by default
a new transaction is started for each call, but you can disallow this, in
which case exceptions are thrown for calls without an active transaction:

[source,java,indent=0]
db.setAllowImplicitTransactions(false);

Nested transactions
~~~~~~~~~~~~~~~~~~~

Nested transactions are supported if your database supports them:

[source,java,indent=0]
----
        db.withTransaction(Propagation.NESTED, tx -> {
            ...
        });
----

Miscellaneous features
----------------------

Large objects
~~~~~~~~~~~~~

You can stream large objects (blobs and clobs) to database by just passing {jdkJavadocBase}java/io/InputStream.html[InputStream]
or {jdkJavadocBase}java/io/Reader.html[Reader] to query. Similarly you can read them by asking back for InputStream
or Reader.

[source,java,indent=0]
----
        try (InputStream in = new FileInputStream(name)) {
            db.update("insert into my_file (name, contents) values (?,?)", name, in);
        }

        try (InputStream in = db.findUnique(InputStream.class,
                                "select contents from my_file where name=?", name)) {
            ...
        }
----

WARNING: Note that the returned InputStream or Reader is only valid for the duration of the active transaction.

Custom type-conversions
~~~~~~~~~~~~~~~~~~~~~~~

Sometimes you need to convert database values to your own custom types and vice versa. To do that,
you can register your own {javadocBase}org/dalesbred/instantiation/TypeConversion.html[TypeConversion]-implementations
to {javadocBase}org/dalesbred/instantiation/TypeConversionRegistry.html[TypeConversionRegistry]:

[source,java,indent=0]
----
        TypeConversionRegistry conversions = db.getTypeConversionRegistry();
        conversions.registerConversionFromDatabaseType(new StringToEmailAddressConversion());
        conversions.registerConversionToDatabaseType(new EmailAddressToStringConversion());
----

You can register type-conversions using lambdas or method references as well:

[source,java,indent=0]
----
        TypeConversionRegistry conversions = db.getTypeConversionRegistry();

        // register conversions from database and to database types separately
        conversions.registerNonNullConversionFromDatabaseType(
            String.class, EmailAddress.class, MyConversions::stringToEmail);
        conversions.registerNonNullConversionToDatabaseType(
            EmailAddress.class, String.class, MyConversions::emailToString);

        // or register both conversions with one call
        conversions.registerNonNullConversions(
            String.class, EmailAddress.class, MyConversions::stringToEmail, MyConversions::emailToString);
----


Custom instantiators
~~~~~~~~~~~~~~~~~~~~

Sometimes you have objects that you can't instantiate using just constructors and setters, but you'd
still like to be able to build from results. You can register custom instantiators for such objects:

[source,java,indent=0]
----
        db.getInstantiatorRegistry().registerInstantiator(Foo.class, new Instantiator<Foo>() {
            @Override
            public Foo instantiate(@NotNull InstantiatorArguments arguments) {
                List<?> args = arguments.getValues();
                FooBuilder fooBuilder = new FooBuilder();
                fooBuilder.setBar(args.get(0));
                fooBuilder.setBaz(args.get(1));
                return fooBuilder.build();
            }
        });
----

Dalesbred will use this instantiator in place of the custom instantiator whenever it needs to build
results of type `Foo`.

Integrations
------------

Java
~~~~

Dalesbred provides builtin type <<_custom_type_conversions,type-conversions>> for the following classes:

[frame="topbot",options="header"]
|====
| Model type                       |       | Database type
| java.net.URI                     | <- -> | String
| java.net.URL                     | <- -> | String
| java.util.TimeZone               | <- -> | String
| Short/Integer/Long/Float/Double  | <-    | Number
| BigInteger/BigDecimal            | <-    | Number
| BigInteger                       |    -> | BigDecimal
| String/java.io.Reader            | <-    | Clob
| byte/java.io.InputStream         | <-    | Blob
| org.w3c.dom.Document             | <-    | SQLXML
| java.time.Instant                | <- -> | Timestamp
| java.time.LocalDateTime          | <- -> | Timestamp
| java.time.LocalTime              | <- -> | Time
| java.time.ZoneId                 | <- -> | String
| java.time.LocalDate              | <- -> | java.util.Date/java.sql.Date
|====


Joda-Time
~~~~~~~~~

If from http://www.joda.org/joda-time/[Joda-Time] is detected on classpath, Dalesbred will automatically
register <<_custom_type_conversions,type-conversions>> between http://www.joda.org/joda-time/[Joda-Time]'s
{jodaJavadocBase}org/joda/time/DateTime.html[DateTime], {jodaJavadocBase}org/joda/time/LocalDate.html[LocalDate]
and {jodaJavadocBase}org/joda/time/LocalTime.html[LocalTime] to {jdkJavadocBase}java/sql/Timestamp.html[java.sql.Timestamp],
{jdkJavadocBase}java/sql/Date.html[java.sql.Date] and {jdkJavadocBase}java/sql/Time.html[java.sql.Time].

Spring
~~~~~~

Dalesbred has support for integration with http://projects.spring.io/spring-framework/[Spring Framework]
and its transaction management. To integrate Dalesbred, create a configuration class inheriting from
{javadocBase}org/dalesbred/support/spring/DalesbredConfigurationSupport.html[DalesbredConfigurationSupport]
and specify beans for {jdkJavadocBase}javax/sql/DataSource.html[DataSource] and
{springJavadocBase}org/springframework/transaction/PlatformTransactionManager.html[PlatformTransactionManager].
A minimal configuration would therefore be something like the following:

[source,java,indent=0]
----
        @Configuration
        @EnableTransactionManagement
        public class MyDatabaseConfiguration extends DalesbredConfigurationSupport {

            @Bean
            public DataSource dataSource() {
                return new JndiDataSourceLookup().getDataSource("jdbc/my-database");
            }

            @Bean
            public PlatformTransactionManager transactionManager() {
                return new DataSourceTransactionManager(dataSource());
            }
        }
----

After this you can inject {javadocBase}org/dalesbred/Database.html[Database] normally in your beans.

Guice
~~~~~

Dalesbred has support for integration with https://code.google.com/p/google-guice/[Guice 3]. Provided
that you have defined a binding for `DataSource`, you can just pass in
{javadocBase}org/dalesbred/support/guice/DataSourceDatabaseModule.html[DataSourceDatabaseModule]
when constructing your injector and you'll get automatic support for annotation based transactions and can
@Inject your database wherever you need it.

[source,java,indent=0]
----
        Injector injector = Guice.createInjector(new DataSourceDatabaseModule(), new MyOtherModule());
----

See the {javadocBase}[Javadoc] of the modules for details of their configuration.

IntelliJ IDEA
~~~~~~~~~~~~~

If you're using https://www.jetbrains.com/idea/[IntelliJ IDEA], check out
https://github.com/EvidentSolutions/dalesbred-idea-plugin[Dalesbred IDEA Plugin],
which provides inspections for common errors (e.g. mismatch between query parameters
and query).

Test support
------------

By including the _dalesbred-junit_ artifact in your project as a test dependency,
you'll get support for writing transactional test cases:

[source,java,indent=0]
----
        public class MyTest {

            private final Database db =
                TestDatabaseProvider.databaseForProperties("testdb.properties");

            @Rule
            public final TransactionalTests tx = new TransactionalTests(db);

            @Test
            public void simpleTest() {
                assertEquals("hello, world!",
                    db.queryForUnique(String.class "select 'hello, world!'");
            }
        }
----

More examples
-------------

Check out the test cases under https://github.com/EvidentSolutions/dalesbred/tree/master/dalesbred/src/test/java/org/dalesbred[dalesbred/src/test/java]
for more usage examples.

Downloading
-----------

Gradle
~~~~~~

Add the following to your project:

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
        dependencies {
            compile 'org.dalesbred:dalesbred:{revnumber}'
        }

        repositories {
            mavenCentral()
        }
----

For the JUnit test-support classes, add the following:

[source,groovy,indent=0]
[subs="verbatim,attributes"]
----
        dependencies {
            testCompile 'org.dalesbred:dalesbred-junit:{revnumber}'
        }
----

Maven
~~~~~

Dalesbred is available on the central Maven repository, so just add the following
dependency to your `pom.xml`:

[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
        <dependency>
            <groupId>org.dalesbred</groupId>
            <artifactId>dalesbred</artifactId>
            <version>{revnumber}</version>
        </dependency>
----

For the JUnit test-support classes, add the following:

[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
        <dependency>
            <groupId>org.dalesbred</groupId>
            <artifactId>dalesbred-junit</artifactId>
            <version>{revnumber}</version>
            <scope>test</scope>
        </dependency>
----

Without dependency manager
~~~~~~~~~~~~~~~~~~~~~~~~~~

To use Dalesbred without a dependency management system, you'll need to
download http://repo1.maven.org/maven2/org/dalesbred/dalesbred/{revnumber}/dalesbred-{revnumber}.jar[dalesbred-{revnumber}.jar]
and it to your classpath. There are no other required dependencies.

Contributors
------------

- https://bitbucket.org/christophgr[Christoph Gritschenberger]

Attributions
------------

Image of dalesbred used on the website is by http://www.flickr.com/photos/48235612@N00/338947492[NicePics on Flickr]
and is used by http://creativecommons.org/licenses/by-sa/2.0/[CC BY-SA 2.0].
